version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: djp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobsdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: djp-redis
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: djp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - redis
      - postgres

  grafana:
    image: grafana/grafana
    container_name: djp-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
